########################################################################
# 1) Build Frontend (Node + Vite)                                      #
########################################################################
ARG BUILDPLATFORM
FROM --platform=linux/arm/v7 node:23.11-bullseye-slim AS node-builder

WORKDIR /app
COPY app/package.json app/package-lock.json ./

ENV VITE_APP_ENV=production


RUN apt-get update \
  && apt-get install -y python3 make g++ \
  && npm install --ignore-scripts \
  && npm rebuild \
  && rm -rf /var/lib/apt/lists/*


COPY app/ .
RUN npm run build

########################################################################
# 2) Build Backend (Go)                                                #
########################################################################
FROM --platform=linux/arm/v7 golang:1.23-bullseye AS go-builder

ENV CGO_ENABLED=1
ENV GOOS=linux
ENV GOARCH=arm
ENV GOARM=7

WORKDIR /app
COPY api/go.mod api/go.sum ./
RUN go mod download

COPY api/ .
RUN apt-get update && \
    apt-get install -y gcc-arm-linux-gnueabihf libc6-dev-armhf-cross && \
    export CC=arm-linux-gnueabihf-gcc && \
    go build -o api ./main.go && \
    rm -rf /var/lib/apt/lists/*

########################################################################
# 3) Final image (Debian)                                              #
########################################################################
FROM --platform=linux/arm/v7 debian:bullseye-slim

WORKDIR /app

ENV ENV="production"
ENV BOOK_DIRECTORY="data"
ENV COVER_DIRECTORY="covers"
ENV DATABASE_PATH="comics.db"
ENV JWT_TOKEN="your_jwt_secret"
ENV API_HOST="https://axolotl.bastiengrisvard.com"
ENV GIN_MODE=release

COPY --from=go-builder /app/api    ./api
COPY --from=node-builder /app/dist ./dist


RUN apt-get update \
 && apt-get install -y ca-certificates \
 && rm -rf /var/lib/apt/lists/*

EXPOSE 8080
CMD ["./api"]
